# Generated by Django 3.1 on 2020-09-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apppro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='image',
            field=models.ImageField(default='', upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='test',
            name='price',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4),
        ),
    ]
